const { MYSQL_HOST,MYSQL_USER,MYSQL_PASSWORD,MYSQL_PORT,MYSQL_DATABASE } = require("./keys.dev");


module.exports = {
  MYSQL_HOST: MYSQL_HOST,
  MYSQL_USER: MYSQL_USER,
  MYSQL_PASSWORD: MYSQL_PASSWORD,
  MYSQL_DATABASE: MYSQL_DATABASE,
  MYSQL_PORT:MYSQL_PORT
};
